
"""
filegroup(
    name="sim_messages_swig_i",
    srcs=glob(["*.i"])
)

cc_library(
    name="sim_messages",
    hdrs=glob(["*.h"]),
    textual_hdrs=glob(["*.h"]),
    strip_include_prefix="/src/simulation",
    visibility=["//visibility:public"],
)
"""