#add_subdirectory(device_interface)
#add_subdirectory(dynamics)
#add_subdirectory(environment)
add_subdirectory(framework)
#add_subdirectory(navigation)
#add_subdirectory(onboard_data_handling)
#add_subdirectory(power)
#add_subdirectory(sensors)
#add_subdirectory(sim_fsw_interface_messages)
#add_subdirectory(sim_messages)
#add_subdirectory(sim_synch)
add_subdirectory(utilities)
#add_subdirectory(utilities_self_check)
#add_subdirectory(vizard)